[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'

# ir based compilation
via_ir = true

[invariant]
# fail_on_revert = true
# show_metrics = true